export const errorCatalog = {
  RATE_LIMITED: { statusCode: 429, message: "Quá nhiều yêu cầu. Vui lòng thử lại sau." },
  SETTINGS_VERSION_CONFLICT: { statusCode: 409, message: "Cài đặt đã được cập nhật ở nơi khác" },
  SCHEDULE_OUTSIDE_WORKING_HOURS: { statusCode: 400, message: "Lịch làm việc phải nằm trong giờ làm việc của hệ thống" },
  APPOINTMENT_DATE_OUT_OF_RANGE: { statusCode: 400, message: "Thời gian đặt lịch nằm ngoài khoảng cho phép" },
  APPOINTMENT_FORBIDDEN: { statusCode: 403, message: "Không có quyền thao tác với lịch hẹn này" },
  APPOINTMENT_NOT_CANCELLABLE: { statusCode: 409, message: "Lịch hẹn không còn có thể hủy" },
  APPOINTMENT_NOT_COMPLETABLE: { statusCode: 409, message: "Lịch hẹn không còn có thể hoàn thành" },
  APPOINTMENT_NOT_CONFIRMABLE: { statusCode: 409, message: "Lịch hẹn không còn có thể xác nhận" },
  APPOINTMENT_NOT_FOUND: { statusCode: 404, message: "Không tìm thấy lịch hẹn" },
  APPOINTMENT_NOT_REJECTABLE: { statusCode: 409, message: "Lịch hẹn không còn có thể từ chối" },
  APPOINTMENT_NOT_STARTED: { statusCode: 409, message: "Chưa đến giờ bắt đầu lịch hẹn" },
  APPOINTMENT_SLOT_UNAVAILABLE: { statusCode: 409, message: "Khung giờ không còn khả dụng" },
  AVATAR_REQUIRED: { statusCode: 400, message: "Cần gửi ảnh đại diện" },
  AVATAR_TOO_LARGE: { statusCode: 400, message: "Ảnh đại diện không được vượt quá 5 MB" },
  AVATAR_UPLOAD_FAILED: { statusCode: 502, message: "Không thể tải ảnh đại diện" },
  CANCELLATION_TOO_LATE: { statusCode: 409, message: "Đã quá thời hạn hủy lịch hẹn" },
  DOCTOR_ALREADY_IN_SPECIALTY: { statusCode: 409, message: "Bác sĩ đã thuộc chuyên khoa này" },
  DOCTOR_ALREADY_REVIEWED: { statusCode: 409, message: "Bệnh nhân đã đánh giá bác sĩ này" },
  DOCTOR_EMAIL_REQUIRED: { statusCode: 400, message: "Bác sĩ chưa có email hợp lệ" },
  DOCTOR_NOT_AVAILABLE: { statusCode: 400, message: "Bác sĩ không tồn tại hoặc đã bị khóa" },
  DOCTOR_NOT_FOUND: { statusCode: 404, message: "Không tìm thấy bác sĩ" },
  DOCTOR_NOT_IN_SPECIALTY: { statusCode: 404, message: "Bác sĩ không thuộc chuyên khoa này" },
  DOCTOR_PROFILE_NOT_FOUND: { statusCode: 404, message: "Không tìm thấy hồ sơ bác sĩ" },
  EMAIL_ALREADY_EXISTS: { statusCode: 409, message: "Email đã được sử dụng" },
  EMAIL_REQUIRED: { statusCode: 400, message: "Cần cập nhật email trước khi bật thông báo qua email" },
  EMAIL_SEND_FAILED: { statusCode: 502, message: "Không thể gửi email" },
  FIREBASE_ACCOUNT_ALREADY_LINKED: { statusCode: 409, message: "Tài khoản Firebase đã liên kết với bệnh nhân khác" },
  FIREBASE_ACCOUNT_MISMATCH: { statusCode: 401, message: "Tài khoản Firebase không khớp với bệnh nhân" },
  FORBIDDEN: { statusCode: 403, message: "Không có quyền truy cập" },
  GOOGLE_MEET_CLOSE_FAILED: { statusCode: 502, message: "Không thể kết thúc phòng Google Meet" },
  GOOGLE_MEET_CREATE_FAILED: { statusCode: 502, message: "Không thể tạo phòng Google Meet" },
  GOOGLE_MEET_NOT_CONFIGURED: { statusCode: 503, message: "Google Meet chưa được cấu hình" },
  INTERNAL_SERVER_ERROR: { statusCode: 500, message: "Lỗi hệ thống" },
  INVALID_AVATAR_TYPE: { statusCode: 400, message: "Ảnh đại diện chỉ hỗ trợ JPEG, PNG hoặc WebP" },
  INVALID_AVATAR_UPLOAD: { statusCode: 400, message: "Tệp ảnh đại diện không hợp lệ" },
  INVALID_CREDENTIALS: { statusCode: 401, message: "Email hoặc mật khẩu không đúng" },
  INVALID_CURRENT_PASSWORD: { statusCode: 400, message: "Mật khẩu hiện tại không đúng" },
  INVALID_FIREBASE_TOKEN: { statusCode: 401, message: "Firebase ID token không hợp lệ hoặc đã hết hạn" },
  INVALID_PASSWORD_OTP: { statusCode: 400, message: "OTP không hợp lệ" },
  INVALID_REFRESH_TOKEN: { statusCode: 401, message: "Refresh token không hợp lệ" },
  INVALID_STATISTICS_RANGE: { statusCode: 400, message: "Khoảng thời gian thống kê không hợp lệ" },
  MENU_ITEM_INVALID: { statusCode: 400, message: "Mục menu không thuộc vai trò hoặc đã thay đổi" },
  MENU_ITEM_NOT_FOUND: { statusCode: 404, message: "Không tìm thấy mục menu" },
  MENU_ITEM_PROTECTED: { statusCode: 400, message: "Không thể xóa hoặc ẩn mục menu được bảo vệ" },
  MENU_NOT_INITIALIZED: { statusCode: 503, message: "Menu chưa được khởi tạo" },
  MENU_ORDER_INVALID: { statusCode: 400, message: "Danh sách sắp xếp menu không hợp lệ" },
  MENU_PATH_EXISTS: { statusCode: 409, message: "Trang đã có trong menu" },
  MENU_PATH_NOT_ALLOWED: { statusCode: 400, message: "Trang không hợp lệ với vai trò này" },
  MENU_VERSION_CONFLICT: { statusCode: 409, message: "Menu đã thay đổi, vui lòng tải lại trước khi lưu" },
  NO_COMPLETED_APPOINTMENT: { statusCode: 409, message: "Cần có ít nhất một buổi khám hoàn thành với bác sĩ" },
  NOTIFICATION_NOT_FOUND: { statusCode: 404, message: "Không tìm thấy thông báo" },
  PASSWORD_OTP_ALREADY_USED: { statusCode: 400, message: "OTP đã được sử dụng" },
  PASSWORD_OTP_EXPIRED: { statusCode: 400, message: "OTP đã hết hạn" },
  PASSWORD_OTP_MAX_ATTEMPTS: { statusCode: 429, message: "Đã vượt quá số lần nhập OTP cho phép" },
  PASSWORD_OTP_NOT_FOUND: { statusCode: 400, message: "Không tìm thấy OTP hợp lệ" },
  PASSWORD_OTP_RESEND_TOO_SOON: { statusCode: 429, message: "Vui lòng chờ trước khi gửi lại OTP" },
  PASSWORD_UNCHANGED: { statusCode: 400, message: "Mật khẩu mới phải khác mật khẩu hiện tại" },
  PATIENT_NOT_FOUND: { statusCode: 404, message: "Không tìm thấy bệnh nhân" },
  PATIENT_PROFILE_NOT_FOUND: { statusCode: 404, message: "Không tìm thấy hồ sơ bệnh nhân" },
  PATIENT_TIME_CONFLICT: { statusCode: 409, message: "Bệnh nhân đã có lịch trong khung giờ này" },
  PHONE_ALREADY_EXISTS: { statusCode: 409, message: "Số điện thoại đã tồn tại" },
  REFRESH_TOKEN_EXPIRED: { statusCode: 401, message: "Refresh token đã hết hạn" },
  REVIEW_ALREADY_REPLIED: { statusCode: 409, message: "Đánh giá đã được phản hồi" },
  REVIEW_HIDDEN: { statusCode: 409, message: "Không thể phản hồi đánh giá đang bị ẩn" },
  REVIEW_NOT_FOUND: { statusCode: 404, message: "Không tìm thấy đánh giá" },
  SCHEDULE_OVERRIDE_IN_PAST: { statusCode: 400, message: "Không thể thay đổi khoảng thời gian đã kết thúc" },
  SCHEDULE_OVERRIDE_NOT_FOUND: { statusCode: 404, message: "Không tìm thấy thay đổi lịch" },
  SCHEDULE_OVERRIDE_OVERLAP: { statusCode: 409, message: "Khoảng thời gian đã có thay đổi lịch khác" },
  SLOT_ALREADY_RESERVED: { statusCode: 409, message: "Khung giờ vừa được người khác đặt" },
  SPECIALTY_ALREADY_EXISTS: { statusCode: 409, message: "Mã hoặc tên chuyên khoa đã tồn tại" },
  SPECIALTY_DISABLED: { statusCode: 409, message: "Chuyên khoa đã bị vô hiệu hóa" },
  SPECIALTY_NOT_AVAILABLE: { statusCode: 400, message: "Một hoặc nhiều chuyên khoa không tồn tại hoặc đã bị vô hiệu hóa" },
  SPECIALTY_NOT_FOUND: { statusCode: 404, message: "Không tìm thấy chuyên khoa" },
  STATISTICS_RANGE_TOO_LARGE: { statusCode: 400, message: "Khoảng thống kê không được vượt quá 366 ngày" },
  TOKEN_REVOKED: { statusCode: 401, message: "Phiên đăng nhập không còn hợp lệ" },
  UNAUTHORIZED: { statusCode: 401, message: "Chưa đăng nhập hoặc phiên đăng nhập không hợp lệ" },
  USER_DISABLED: { statusCode: 403, message: "Tài khoản đã bị khóa" },
  USER_NOT_FOUND: { statusCode: 404, message: "Không tìm thấy tài khoản" },
  USER_STATUS_CHANGED: { statusCode: 409, message: "Trạng thái tài khoản đã được thay đổi" },
  USER_STATUS_UNCHANGED: { statusCode: 409, message: "Trạng thái tài khoản không thay đổi" },
  VALIDATION_ERROR: { statusCode: 400, message: "Dữ liệu không hợp lệ" },
  WEEK_START_NOT_MONDAY: { statusCode: 400, message: "Ngày bắt đầu tuần phải là thứ Hai" },
} as const;

export type ApiErrorCode = keyof typeof errorCatalog;
